actually fail the test that fails

diff --git a/.github/workflows/10-execution-flow.yml b/.github/workflows/10-execution-flow.yml
--- a/.github/workflows/10-execution-flow.yml
+++ b/.github/workflows/10-execution-flow.yml
@@ -21,7 +21,9 @@ jobs:
         run: echo "Running unit tests..."
       - name: Failing tests
         if: ${{ github.event.inputs.pass-unit-tests == 'false' }}
-        run: echo "failing tests..."
+        run: |
+          echo "failing tests..."
+          exit 1
   deploy-nonprod:
     runs-on: ubuntu-latest
     needs: 
