modify matrices

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -5,9 +5,17 @@ jobs:
     backwards-compatibility:
       runs-on: ubuntu-latest
       strategy:
+#        fail-fast: false
         matrix:
           node-version: [18.x, 20.x, 21.x]
-          os: [ubuntu-latest, windows-latest]
+          os: 
+            - ubuntu-latest
+            - windows-latest
+          include:
+            - os: ubuntu-latest-21.x
+              tag: experimental
+            - os: ubuntu-latest
+              node-version: 16.x
       steps:
         # - name: Checkout code
         #   uses: actions/checkout@v4
@@ -15,6 +23,13 @@ jobs:
           uses: actions/setup-node@v4
           with:
             node-version: ${{ matrix.node-version }}
+        - name: fail if experimental
+          if: ${{ matrix.tag == 'experimental' }}
+          run: exit 1
         - name: Perform some tests
-          run: echo "Running on ${{ matrix.os }} with Node.js version ${{ matrix.node-version }}"
+          run: |
+            echo "Running on ${{ matrix.os }} with Node.js version ${{ matrix.node-version }}"
+            sleep 10
+        - name: Perform some tests
+          run: echo "Uploading Test Results"
         
